run:
  timeout: 10m

linters:
  enable:
    - bodyclose
#    - goimports
    - unconvert
#    - unparam
    - scopelint
    - dupl
    - interfacer
    - stylecheck

issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1003:"
    - linters:
        - scopelint
      text: 'Using the variable on range scope `tc` in function literal'
