run:
  timeout: 10m

linters:
  enable:
    - bodyclose
#    - goimports
    - unconvert
#     - unparam
    - scopelint
    - dupl
    - interfacer
    - stylecheck

issues:
  exclude-rules:
    # Exclude linter specific checks
    - linters:
        - stylecheck
      text: "ST1003:"
