# https://goreleaser.com
project_name: autoscan

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    main: ./cmd/autoscan
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

# MacOS Universal Binaries
universal_binaries:
  -
    replace: true

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"