# https://goreleaser.com
project_name: autoscan

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/autoscan
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore: # remove once sqlite package supports darwin/arm64 (see: https://pkg.go.dev/modernc.org/sqlite?utm_source=godoc)
      - goos: darwin
        goarch: arm64
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"