name: Remove old artifacts

on:
  schedule:
    # Every every day at 02:00 (UTC)
    - cron: '0 2 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 days'
          skip-recent: 3