name: Docker Cleanup

on:
  delete:
    branches:
      - *
  pull_request:
    types: [closed, removed]

jobs:
  cleanup_branch:
    if: startsWith(github.ref_type, 'branch') == true
    runs-on: ubuntu-latest
    steps:
      - name: Determine docker tag
        id: dockertag
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/heads/}"

      - name: Remove branch docker tag
        shell: bash
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ steps.dockertag.outputs.tag }}
        run: |
          docker run --rm lumir/remove-dockerhub-tag --user "$username" --password "$password" cloudb0x/autoscan:$tag

  cleanup_pr:
    if: startsWith(github.ref, 'refs/pull/') == true
    runs-on: ubuntu-latest
    steps:
      - name: Determine pull request tag
        id: githubpr
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/pull/}"

      - name: Determine docker tag
        uses: frabert/replace-string-action@master
        id: dockertag
        with:
          pattern: '[:\.]+'
          string: "${{ steps.githubpr.outputs.tag }}"
          replace-with: '-'
          flags: 'g'

      - name: Remove pull request docker tag
        shell: bash
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ steps.dockertag.outputs.replaced }}
        run: |
          docker run --rm lumir/remove-dockerhub-tag --user "$username" --password "$password" cloudb0x/autoscan:pr-$tag

