name: Docker Cleanup

on:
  pull_request:
    types: [closed, removed]
  delete:

jobs:
  cleanup_branch:
    if: startsWith(github.event.ref_type, 'branch') == true
    runs-on: ubuntu-latest
    steps:
      - name: Sanitize branch docker tag
        uses: frabert/replace-string-action@master
        id: dockertag
        with:
          pattern: '[:\.\/]+'
          string: "${{ github.event.ref }}"
          replace-with: '-'
          flags: 'g'

      - name: Remove branch docker tag
        shell: bash
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ steps.dockertag.outputs.replaced }}
        run: |
          docker run --rm lumir/remove-dockerhub-tag --user "$username" --password "$password" cloudb0x/autoscan:$tag

  cleanup_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Remove pull request docker tag
        shell: bash
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ github.event.number }}
        run: |
          docker run --rm lumir/remove-dockerhub-tag --user "$username" --password "$password" cloudb0x/autoscan:pr-$tag-merge
